package hibernate.pojo;
// Generated Apr 10, 2014 3:52:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GmSite generated by hbm2java
 */
public class GmSite implements java.io.Serializable {

	private Integer id;
	private String url;
	private int port;
	private String description;
	private String display;

	public GmSite() {
	}

	public String getAddress(){
		return url+":"+port;
	}
	
	public GmSite(String url, int port, String display) {
		this.url = url;
		this.port = port;
		this.display = display;
	}

	public GmSite(String url, int port, String description, String display) {
		this.url = url;
		this.port = port;
		this.description = description;
		this.display = display;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

}
