package hibernate.pojo;
// Generated Apr 10, 2014 3:52:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GmStatus generated by hbm2java
 */
public class GmStatus implements java.io.Serializable {

	private GmStatusId id;
	private String ipofib;
	private double cpuuseratio;
	private int memtotal;
	private int usedmem;
	private int netsendflow;
	private int netreceiveflow;
	private int ibsendflow;
	private int ibreceiveflow;

	public GmStatus() {
	}

	public GmStatus(GmStatusId id, String ipofib, double cpuuseratio,
			int memtotal, int usedmem, int netsendflow, int netreceiveflow,
			int ibsendflow, int ibreceiveflow) {
		this.id = id;
		this.ipofib = ipofib;
		this.cpuuseratio = cpuuseratio;
		this.memtotal = memtotal;
		this.usedmem = usedmem;
		this.netsendflow = netsendflow;
		this.netreceiveflow = netreceiveflow;
		this.ibsendflow = ibsendflow;
		this.ibreceiveflow = ibreceiveflow;
	}
	
	public double getMemusedratio(){
		return 1.0 * usedmem / memtotal;
	}
	
	public GmStatusId getId() {
		return this.id;
	}

	public void setId(GmStatusId id) {
		this.id = id;
	}

	public String getIpofib() {
		return this.ipofib;
	}

	public void setIpofib(String ipofib) {
		this.ipofib = ipofib;
	}

	public double getCpuuseratio() {
		return this.cpuuseratio;
	}

	public void setCpuuseratio(double cpuuseratio) {
		this.cpuuseratio = cpuuseratio;
	}

	public int getMemtotal() {
		return this.memtotal;
	}

	public void setMemtotal(int memtotal) {
		this.memtotal = memtotal;
	}

	public int getUsedmem() {
		return this.usedmem;
	}

	public void setUsedmem(int usedmem) {
		this.usedmem = usedmem;
	}

	public int getNetsendflow() {
		return this.netsendflow;
	}

	public void setNetsendflow(int netsendflow) {
		this.netsendflow = netsendflow;
	}

	public int getNetreceiveflow() {
		return this.netreceiveflow;
	}

	public void setNetreceiveflow(int netreceiveflow) {
		this.netreceiveflow = netreceiveflow;
	}

	public int getIbsendflow() {
		return this.ibsendflow;
	}

	public void setIbsendflow(int ibsendflow) {
		this.ibsendflow = ibsendflow;
	}

	public int getIbreceiveflow() {
		return this.ibreceiveflow;
	}

	public void setIbreceiveflow(int ibreceiveflow) {
		this.ibreceiveflow = ibreceiveflow;
	}

}
