package hibernate.pojo;
// Generated Apr 10, 2014 3:52:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GmStatusId generated by hbm2java
 */
public class GmStatusId implements java.io.Serializable {

	private Date id;
	private String hostname;

	public GmStatusId() {
	}

	public GmStatusId(Date id, String hostname) {
		this.id = id;
		this.hostname = hostname;
	}

	public Date getId() {
		return this.id;
	}

	public void setId(Date id) {
		this.id = id;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GmStatusId))
			return false;
		GmStatusId castOther = (GmStatusId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getHostname() == castOther.getHostname()) || (this
						.getHostname() != null
						&& castOther.getHostname() != null && this
						.getHostname().equals(castOther.getHostname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getHostname() == null ? 0 : this.getHostname().hashCode());
		return result;
	}

}
