package hibernate.pojo;
// Generated Apr 10, 2014 3:52:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GmUser generated by hbm2java
 */
public class GmUser implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private int level;

	public GmUser() {
	}

	public GmUser(String name, String password, int level) {
		this.name = name;
		this.password = password;
		this.level = level;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
