#!/bin/bash
hostname=`hostname`
testparm=`gluster peer status 2>/dev/null|grep Connected`
if [ -n "$testparm" ];then
node_stat="Connected"
else
node_stat="Offline"
fi
host_ip=`cat /etc/hosts|awk '$2==hostname {print $1}' hostname=$hostname`
	echo "$hostname $node_stat $host_ip"
peer_stat()
{
	gluster peer status|grep -v Number|sed 's/.*(\(.*\)).*/\1/'g|awk -v RS="" '{print $2" "$5}'
}
peerinfo=`gluster peer status`
if [ "$peerinfo" = "No peers present" ];then
	exit 0
fi
peer_stat|while read line
do
	if [ -z "`echo $line|awk '{print $1}'|grep "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"`" ];then
		peer_name=`echo $line|awk '{print $1}'`
		peer_ip=`cat /etc/hosts|awk '$2==peer_name {print $1}' peer_name=$peer_name`
		peer_stat=`echo $line|awk '{print $2}'`
	else 
		peer_ip=`echo $line|awk '{print $1}'`
		peer_name=`cat /etc/hosts|awk '$1==peer_ip {print $2}' peer_ip=$peer_ip`
		peer_stat=`echo $line|awk '{print $2}'`
	fi
	echo "$peer_name $peer_stat $peer_ip"
done
